CandidateInterviewer/DK.Web/ViewModels/HomeViewModel.cs
using System.Collections.Generic;

namespace DK.Web.ViewModels
{
    public class HomeViewModel
    {
        public List<CategoryViewModel> Catgories { get; set; }
    }
}

CandidateInterviewer/DK.Web/ViewModels/ResultViewModel.cs
using DK.DataAccess.Enums;
using System;

namespace DK.Web.ViewModels
{
    public class ResultViewModel
    {
        public int InterviewId { get; set; }

        public string CandidateFullName { get; set; }

        public string CandidateDescription { get; set; }   

        public string ExamName { get; set; }

        public ExamType Type { get; set; }

        public string Email { get; set; }

        public int Score { get; set; }

        public string ExamTypeLogo { get; set; }

        public string ExamLogo { get; set; }

        public DateTime Date { get; set; }
    }
}

CandidateInterviewer/DK.Web/Controllers/HomeController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DK.DataAccess.Interfaces;
using System.Linq;
using DK.Web.ViewModels;
using System.Collections.Generic;
using DK.Web.Managers;

namespace DK.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IInterviewService _interviewService;
        private readonly IUserService _userService;

        public HomeController(IInterviewService interviewService, IUserService userService)
        {
            _interviewService = interviewService;
            _userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var categories = await _interviewService.GetCategoriesAsync();
            var viewModel = ViewModelBuilder.GetHomeViewModel(categories);

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Interviews()
        {
            var categories = await _interviewService.GetCategoriesAsync();
            var viewModel = ViewModelBuilder.GetInterviewsViewModel(categories);

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Results()
        {
            var interviews = await _interviewService.GetPassedInterviewsAsync();
            var candidates = await _userService.GetCandidatesAsync();

            if (interviews?.Any() != true || candidates?.Any() != true)
            {
                return RedirectToAction(nameof(HomeController.Error));
            }

            var viewModels = new List<ResultViewModel>();

            foreach (var interview in interviews)
            {
                var candidate = candidates.FirstOrDefault(e => e.Id == interview.CandidateId);

                if (candidate != null)
                {
                    var exam = await _interviewService.GetExamAsync(interview.ExamId);
                    viewModels.Add(ViewModelBuilder.GetResultViewModels(interview, candidate, exam));
                }
            }

            return View(viewModels.OrderByDescending(e => e.Score).ToList());
        }

        [HttpGet]
        public IActionResult Contacts()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CandidateInterviewer/DK.Web/Controllers/InterviewController.cs
using System.Threading.Tasks;
using DK.DataAccess.Interfaces;
using DK.Web.Managers;
using DK.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Collections.Generic;
using DK.DataAccess.Entities;

namespace DK.Web.Controllers
{
    public class InterviewController : Controller
    {
        private readonly IInterviewService _interviewService;
        private readonly IUserService _userService;

        public InterviewController(IInterviewService interviewService, IUserService userService)
        {
            _interviewService = interviewService;
            _userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int id)
        {
            var category = await _interviewService.GetCategoryAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            var viewModel = ViewModelBuilder.GetInterviewViewModel(category);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(InterviewViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var candidate = await _userService.InitCandidateAsync(model.Candidate.ToCandidateEntity());
            var exam = await _interviewService.GetExamByCategoryAsync(model.Category.Id, model.SelectedExamType);

            if (candidate == null || exam == null)
            {
                return RedirectToAction(nameof(HomeController.Error));
            }

            var interview = await _interviewService.InitInterviewAsync(candidate.Id, exam.Id);

            return RedirectToAction(nameof(Exam), new { id = interview.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Exam(int id)
        {
            var interview = await _interviewService.GetInterviewAsync(id);
            var exam = await _interviewService.GetExamAsync(interview.ExamId);
            var candidate = await _userService.GetCandidateAsync(interview.CandidateId);

            if (exam == null || candidate == null)
            {
                return RedirectToAction(nameof(HomeController.Error));
            }

            var answers = new List<Answer>();
            var examQuestions = await _interviewService.GetQuestionsForExamAsync(interview.ExamId);
            if (examQuestions?.Any() == true)
            {
                foreach (var question in examQuestions)
                {
                    var questionAnswers = await _interviewService.GetAnswersForQuestionAsync(question.Id);
                    if (questionAnswers?.Any() == true)
                    {
                        answers.AddRange(questionAnswers);
                    }
                }
            }

            var viewModel = ViewModelBuilder.GetExamViewModel(interview, exam, candidate, examQuestions, answers);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Exam(ExamViewModel model)
        {
            ModelState.Clear();

            var interview = await _interviewService.GetInterviewAsync(model.InterviewId);
            if (interview != null)
            {
                await _interviewService.SaveResponcesForInterviewAsync(ViewModelBuilder.GetExamResponses(model));
                if (await _interviewService.UpdateInterviewScoreAsync(interview, CalculationManager.CalculateFinalInterviewScore(model.Questions, model.Type)))
                {
                    return RedirectToAction(nameof(Complete), new { id = interview.Id });
                }
            }

            return RedirectToAction(nameof(HomeController.Error));
        }

        [HttpGet]
        public async Task<IActionResult> Complete(int id)
        {
            var interview = await _interviewService.GetInterviewAsync(id);
            var exam = await _interviewService.GetExamAsync(interview.ExamId);
            var candidate = await _userService.GetCandidateAsync(interview.CandidateId);

            if (interview == null || exam == null || candidate == null)
            {
                return RedirectToAction(nameof(HomeController.Error));
            }

            var viewModel = ViewModelBuilder.GetCompleteViewModel(interview, exam, candidate);

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ExamReview(int id)
        {
            var interview = await _interviewService.GetInterviewAsync(id);
            var exam = await _interviewService.GetExamAsync(interview.ExamId);
            var candidate = await _userService.GetCandidateAsync(interview.CandidateId);

            if (exam == null || candidate == null)
            {
                return RedirectToAction(nameof(HomeController.Error));
            }

            var answers = new List<Answer>();
            var examQuestions = await _interviewService.GetQuestionsForExamAsync(interview.ExamId);
            if (examQuestions?.Any() == true)
            {
                foreach (var question in examQuestions)
                {
                    var questionAnswers = await _interviewService.GetAnswersForQuestionAsync(question.Id);
                    if (questionAnswers?.Any() == true)
                    {
                        answers.AddRange(questionAnswers);
                    }
                }
            }

            var responses = await _interviewService.GetResponsesForInterviewAsync(interview.Id);
            var viewModel = ViewModelBuilder.GetExamViewModel(interview, exam, candidate, examQuestions, answers);
            viewModel.Responses = ViewModelBuilder.GetResponseViewModels(responses);

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ExamReview(ExamViewModel model, string submit)
        {
            if (!string.IsNullOrEmpty(submit))
            {
                int questionId = 0;
                var parameters = submit.Split("-");

                if (int.TryParse(parameters[1], out questionId))
                {
                    await _interviewService.UpdateQuestionApprovalAsync(model.InterviewId, questionId, parameters[0] == "approve" ? true : false);
                }
            }

            return RedirectToAction(nameof(ExamReview), new { id = model.InterviewId });
        }
    }
}

CandidateInterviewer/DK.Web/Views/Home/Interviews.cshtml
@model InterviewsViewModel

@using DK.DataAccess.Enums;

@{
    ViewData["Title"] = "Interviews";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var mobileCategories = Model.Categories?.Where(e => e.Type == AreaType.MobileDevelopment)?.ToList();
    var webCategories = Model.Categories?.Where(e => e.Type == AreaType.WebDevelopment)?.ToList();
    var qaCategories = Model.Categories?.Where(e => e.Type == AreaType.QualityAssurance)?.ToList();
}

<div class="service">
    <div class="service__phone"></div><i class="service__icon service__icon--cube-blue bounceInDown animated"></i><i class="service__icon service__icon--cube-yellow bounceInDown animated"></i><i class="service__icon service__icon--platform bounceInDown animated"></i>
</div>

<section class="about about--service">
    <div class="container">
        <div class="about__desc">
            <h2 class="title-h2">Select Interview</h2>
            <h3 class="title-h3">Please select required categories for you and start the test!</h3>
        </div>
    </div>
</section>

<section class="model">
    <div class="container">
        <h2 class="title-h2">Difficulty levels</h2>
        <h3 class="title-h3">To meet the requirements of each unique client, we offer three difficulty levels – Base, Intermediate and Advanced.</h3>
        <div class="model__wrap">
            <div class="model__outer">
                <div class="model__itm">
                    <div class="model__preview model__preview--team">
                        <div class="model__desc">
                            <div class="model__link-outer"><a class="model__link" href="#">Base Exam</a></div>
                            <p class="model__text">Exams for base knowleage level. Perfect for begginers.</p>
                        </div>
                    </div>
                </div>
                <div class="model__itm">
                    <div class="model__preview model__preview--product">
                        <div class="model__desc">
                            <div class="model__link-outer"><a class="model__link" href="#">Intermediate Exam</a></div>
                            <p class="model__text">Medium difficulty exams for candidates with middle experience level.</p>
                        </div>
                    </div>
                </div>
                <div class="model__itm">
                    <div class="model__preview model__preview--service">
                        <div class="model__desc">
                            <div class="model__link-outer"><a class="model__link" href="#">Advanced Exam</a></div>
                            <p class="model__text">The most complex exams for candidates with great experience level.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="development separator"></div>

@{ 
    await Html.RenderPartialAsync("_CategoryList", mobileCategories);
    await Html.RenderPartialAsync("_CategoryList", webCategories);
    await Html.RenderPartialAsync("_CategoryList", qaCategories);
}

<section class="about-ci">
    <div class="container">
        <h2 class="title-h2">Get idea for new test?</h2><a class="btn-b"  asp-area="" asp-controller="Home" asp-action="Contacts"><span>Let us know</span></a>
    </div>
</section>

CandidateInterviewer/DK.Web/Views/Home/Results.cshtml
@model List<ResultViewModel>

@using DK.BusinessLogic.Helpers;
@using DK.DataAccess.Enums;
@using DK.Core;

@{
    ViewData["Title"] = "Results";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="contact" style="padding-top: 220px;">
    <div class="contact__wrap">
        <div class="container no-width">
            <h2 class="title-h2">Score calculation</h2>
            <h3 class="title-h3">Each question has it's score value. If candidate gives the right answer than score will be added to the total sum. Also we use boost coefficients for more complex exams:</h3>
            <div class="contact__outer">
                <div class="contact__itm">
                    <div class="connection connection--contacts">
                        <div class="connection__outer">
                            <div class="connection__top">
                                <img class="connection__icon connection__icon--campaign" src="~/images/@Constants.BASE_TYPE_ICO" />
                                <span class="connection__ttl">@ExamType.Base.GetEnumDisplayName().ToUpper()</span>
                                <p class="connection__text">Exams for base knowleage level.</p>
                                <a class="connection__link" href="#">NO TIME LIMIT</a>
                            </div>
                            <div class="connection__bottom">
                                <a class="btn-b btn-b--small" href="#">
                                    <span>COEFFICIENT: @Constants.BASE_EXAM_COEFFICIENT X</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="contact__itm">
                    <div class="connection connection--contacts">
                        <div class="connection__outer">
                            <div class="connection__top">
                                <img class="connection__icon connection__icon--campaign" src="~/images/@Constants.INTERMEDIATE_TYPE_ICO" />
                                <span class="connection__ttl">@ExamType.Intermediate.GetEnumDisplayName().ToUpper()</span>
                                <p class="connection__text">Medium difficulty exam.</p>
                                <a class="connection__link" href="#">NO TIME LIMIT</a>
                            </div>
                            <div class="connection__bottom">
                                <a class="btn-b btn-b--small" href="#">
                                    <span>COEFFICIENT: @Constants.INTERMEDIATE_EXAM_COEFFICIENT X</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="contact__itm">
                    <div class="connection connection--contacts">
                        <div class="connection__outer">
                            <div class="connection__top">
                                <img class="connection__icon connection__icon--campaign" src="~/images/@Constants.ADVANCED_TYPE_ICO" />
                                <span class="connection__ttl">@ExamType.Advanced.GetEnumDisplayName().ToUpper()</span>
                                <p class="connection__text">Medium difficulty exam.</p>
                                <a class="connection__link" href="#">TIME LIMITED</a>
                            </div>
                            <div class="connection__bottom">
                                <a class="btn-b btn-b--small" href="#">
                                    <span>COEFFICIENT: @Constants.ADVANCED_EXAM_COEFFICIENT X</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="contact__sect-cnt">
    <div class="contact__wrap">
        <div class="container no-width">
            <h2 class="title-h2">Candidate Results</h2>
            <h3 class="title-h3">Sorted by higher score</h3>
            <div class="contact__outer--results">
                @foreach (var interview in Model)
                {
                    <div class="work__itm--results">
                        <div class="work__preview--results" data-value="@interview.Type">
                            <div class="work__preview-row">
                                <div class="work__preview-col--results">
                                    <i class="work__icon">
                                        <img class="work__img" src="/images/@interview.ExamTypeLogo">
                                    </i>
                                    <span class="work__ttl--results @(interview.Type.GetEnumDisplayColorClass())">@interview.Score</span>
                                </div>
                                <div class="work__preview-col">
                                    <img class="exam-logo--results" src="/images/@interview.ExamLogo">
                                </div>
                                <div class="work__preview-col--descr">
                                    <span class="work__ttl">@interview.ExamName</span>
                                    <p class="work__text">@interview.CandidateFullName (@interview.CandidateDescription)</p>
                                    <p class="work__text-email">@interview.Email</p>
                                    <a class="connection__link" href="#">@interview.Date.ToLocalTime().ToShortDateString()</a>
                                    <a class="btn-b btn-b--small work__preview-more" asp-area="" asp-controller="Interview" asp-action="ExamReview" asp-route-id="@interview.InterviewId">
                                        <span>Review Answers</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

<section class="about-ci">
    <div class="container">
        <h2 class="title-h2">Need more statistics?</h2><a class="btn-b" asp-area="" asp-controller="Home" asp-action="Contacts"><span>Contact us</span></a>
    </div>
</section>

CandidateInterviewer/DK.Web/Views/Home/_CategoryList.cshtml
@model List<CategoryViewModel>

@using DK.BusinessLogic.Helpers;

@if (Model?.Any() == true)
{
    <section class="examples">
        <div class="container">
            <h2 class="title-h2">@Model.FirstOrDefault().Type.GetEnumDisplayName()</h2>
            <h3 class="title-h3">Tests for @Model.FirstOrDefault().Type.GetEnumDisplayName().ToLower() specialists.</h3>
            <div class="examples__outer">
                <div class="slider">
                    <div class="slider__outer owl-carousel owl-loaded owl-drag">
                        <div class="owl-stage-outer">
                            <div class="static-stage">
                                @for (int i = 0; i < Model.Count(); i++)
                                {
                                    <div class="owl-item">
                                        <div class="slider__itm">
                                            <div class="connection connection--slider">
                                                <div class="connection__outer">
                                                    <div class="connection__top">
                                                        <div class="connection__wrap">
                                                            <img class="platform__img" src="~/images/@Model[i].Logo" />
                                                        </div>
                                                        <div class="connection__desc">
                                                            <span class="connection__ttl">@Model[i].Name</span>
                                                            <p class="connection__text">@Model[i].Description</p>
                                                        </div>
                                                    </div>
                                                    <div class="connection__bottom">
                                                        <a class="connection__link connection__link--arrow" asp-area="" asp-controller="Interview" asp-action="Index" asp-route-id="@Model[i].Id">
                                                            START THE TEST<span class="connection__link-icon"></span>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                        <div class="owl-nav disabled">
                            <button type="button" role="presentation" class="owl-prev">
                                <span aria-label="Previous">‹</span>
                            </button>
                            <button type="button" role="presentation" class="owl-next">
                                <span aria-label="Next">›</span>
                            </button>
                        </div>
                        <div class="owl-dots">
                            <button role="button" class="owl-dot active">
                                <span></span>
                            </button>
                            <button role="button" class="owl-dot">
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}